public class Main {
    public static void main(String[] args) {
        Cours c1=new Cours("JAVA_BD_4", "Programmation Orientée Objet en Java","Ali",4,3,2);
        Cours c2=new Cours("PYTHON", "Programmation","SARA",2,3,25);
        Cours c3=new Cours("RESAUX", "Signal","Mohammed",4,3,30);
        Etudiant et1=new Etudiant("sara","ss",12345);
        EtudiantBoursier eb1 = new EtudiantBoursier("Hiba", "rr", 23456, 2500);
        EtudiantEtranger ee2 = new EtudiantEtranger("David", "ee", 21689, "Benin","etude","2026-06-12");
        EtudiantRegulier er=new EtudiantRegulier("Lina","ll",45678,"annuel",true);
        GestionEtudiant g=new GestionEtudiant();
        g.ajouterEtudiant(et1);
        g.ajouterEtudiant(ee2);
        g.ajouterEtudiant(er);
        g.ajouterEtudiant(eb1);
        g.afficherTousLesEtudiants();
        g.calculerFraisTotaux();
        g.compterParType();
        System.out.println("_____________");
        System.out.println("Etudiant boursier");
        eb1.afficherInfos();
        eb1.inscrireACours(c1);
        eb1.afficherMesCours();
        System.out.println("_____________");
        System.out.println("Etudiant etranger");
        ee2.afficherInfos();
        System.out.println("_____________");
        System.out.println("Etudiant regulier");
        er.afficherInfos();
        et1.inscrireACours(c1);
        et1.afficherMesCours();
        System.out.println("_____________");
        c1.afficherInfos();
        c2.afficherInfos();
        c3.afficherInfos();
        c1.inscrireEtudiant(et1);
        c2.inscrireEtudiant(et1);
        c1.inscrireEtudiant(et1);
        c1.desinscrireEtudiant();
        System.out.println("_____________");
        System.out.println("taux de remplissage: "+c1.calculerTauxRemplissage());
        Etablissement e1=new Etablissement("Euromed");
        Etablissement e2=new Etablissement("universite");
        System.out.println("_____________");
        e1.ajouterCours(c1);
        e1.ajouterCours(c3);
        e2.ajouterCours(c2);
        e1.afficherCours();
        e2.afficherCours();
        e1.supprimerCours(c3);
        e1.afficherCours();
    }
}
